apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "optivor.fullname" . }}-config
  labels:
    {{- include "optivor.labels" . | nindent 4 }}
data:
  optivor.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
