{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "optivor.fullname" . }}
  labels:
    {{- include "optivor.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.config.storage.s3.access_key_id }}
  OPTIVOR_STORAGE_S3_ACCESS_KEY_ID: {{ .Values.config.storage.s3.access_key_id | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.storage.s3.secret_access_key }}
  OPTIVOR_STORAGE_S3_SECRET_ACCESS_KEY: {{ .Values.config.storage.s3.secret_access_key | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.cache.redis.password }}
  OPTIVOR_CACHE_REDIS_PASSWORD: {{ .Values.config.cache.redis.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.auth.signed_urls.secret }}
  OPTIVOR_AUTH_SIGNED_URLS_SECRET: {{ .Values.config.auth.signed_urls.secret | b64enc | quote }}
  {{- end }}
{{- end }}
